In [1]:
#Week 1 Wednesday ,08.07.2026  — Session 3 Labs: LAB - 

In [7]:
# Lab 1
import numpy as np

def greet(name):
    result = f"Hello, {name}!"
    return result

print(greet("Alice"))


Hello, Alice!


In [11]:
# lab 2

def add_numbers(a,b):
    result = a+b
    return  result
    #print("result = ",result)

add_numbers(15,27)

42

In [16]:
# Lab 3

def calculate_bmi(weight_kg, height_m):
    BMI = weight_kg / ((height_m ** 2))
    return round(BMI,2)

calculate_bmi(60,1.6)   

23.44

In [20]:
# Lab 4

def calculate_total(amount, tax_rate=0.05):
    tax = amount*tax_rate
    total_amount = amount + tax
    return round(total_amount,2)

print(f"Total: {calculate_total(100):.2f}")
print(f"Total: {calculate_total(200, 0.12):.2f}")
    

Total: 105.00
Total: 224.00


In [22]:
# Lab #5

def apply_discount(price, discount_percent):
    discounted_price = price - ((price *discount_percent)/100)
    return (discounted_price)

apply_discount(250,10)    


225.0

In [41]:
# Lab 6

def normalize_name(name):
    nor1 = name.strip()
    nor2 = name.split()
    nor3 = ''.join(nor1)#nor2)
    
    normalized = ' '.join(name.strip().split()).title()
    return normalized

print(normalize_name(" alice johnson "))
print(normalize_name("BOB mcDONALD"))

Alice Johnson
Bob Mcdonald


In [52]:
# Lab 7

def basic_stats(numbers):
    count = len(numbers)
    total = sum(numbers)
    if count>0:
        mean = total/count
    else:
        mean = None
    return count, total, mean

print(basic_stats([10,20,30]))
Count, Total, Mean = (basic_stats([10,20,30]))
print("Count:", Count)
print("Total:", Total)
print("Mean:", Mean)
print(basic_stats([ ]))


    

(3, 60, 20.0)
Count: 3
Total: 60
Mean: 20.0
(0, 0, None)


In [59]:
# Lab 8

def apply_tax(amounts, tax_rate=0.1):
    new_list = []

    for amount in amounts:
        tax = amount*tax_rate
        total_amount = amount + tax
        new_list.append(total_amount)
    return new_list

amounts = [100,200,350]

print(apply_tax(amounts))
print(apply_tax(amounts,0.05))

    
    

[110.0, 220.0, 385.0]
[105.0, 210.0, 367.5]


In [67]:
# Lab 9

def process_score(score, max_score=100):
    if score < 0 or score  > max_score:
        return None
        
    percent = (score/max_score)*100
    return round(percent,1)

print(process_score(85))
print(process_score(150))
print(process_score(-5,50))
print(process_score(5,50))
    
    

85.0
None
None
10.0


In [73]:
# Lab 10

py_list = [10, 20, 30, 40, 50]
array_float = [1.5, 2.5, 3.5]

array = np.array(py_list)
arrayF = np.array(array_float)
print(array)
print(type(array))
print(array.dtype)
print(arrayF)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64
[1.5 2.5 3.5]


In [87]:
# Lab 11
List = [10, 20, 30, 40, 50]

arr = np.array(List)
print ("Array = :", arr)
print ("First Element :", arr[0])
print ("Last Element  :", arr[-1])
print ("Slice 1:3  :", arr[1:4])
print ("Slice 0:3  :", arr[0:4])
print ("Slice 0:2  :", arr[0:3])
print ("Slice 0:5  :", arr[0:5])

Array = : [10 20 30 40 50]
First Element : 10
Last Element  : 50
Slice 1:3  : [20 30 40]
Slice 0:3  : [10 20 30 40]
Slice 0:2  : [10 20 30]
Slice 0:5  : [10 20 30 40 50]


In [96]:
# Lab 12


sales = np.array([120, 250, 90, 400, 60])

high_sales = sales[sales >100]
mask = sales > 100
HS = sales[mask]


print (high_sales)
print (HS)
print ("Count =", len(high_sales))


[120 250 400]
[120 250 400]
Count = 3


In [101]:
# Lab 13

prices = np.array([100.0, 200.0, 300.0])
tax = prices*1.05
discounted = prices - (prices * 0.1) 

print ("taxed : ", tax)
print ("Discounted : ", discounted)


taxed :  [105. 210. 315.]
Discounted :  [ 90. 180. 270.]


In [109]:
# Lab 14

data = np.array([10, 20, 30, 40, 50])

Total =  np.sum(data)
Minimum = np.min(data)
Maximum = np.max(data)
Mean =  np.sum(data)/len(data)

print ("Sum:", Total)
print ("Min:", Minimum)
print ("Max:", Maximum)
print ("Mean:", Mean)

Sum: 150
Min: 10
Max: 50
Mean: 30.0


In [176]:
# Lab 15

raw_sales = [120.0, 250.5, np.nan, -20.0, 400.0, 150.0, 0.0, 300.0]

def clean_sales(arr):
    # Converts input list to a NumPy array of floats
    Float_array = np.array(arr,dtype = float)
    Replaced_array = Float_array.copy()
    
    #Replaces negative and zero values with np.nan
    Replaced_array[Replaced_array <= 0] = np.nan

    #Removes np.nan values and returns the cleaned array
    Cleaned_array =  Replaced_array[~np.isnan(Replaced_array)]
    
    return Float_array , Replaced_array, Cleaned_array
   


def apply_discount_to_large_sales(arr, threshold=200, discount_rate=0.1):

# Apply discount to values greater than threshold
    discounted = arr.copy()
    discounted[discounted > threshold] = discounted[discounted > threshold] * (1 - discount_rate)

    return discounted


def summarize_sales(arr):
    total = arr.sum()
    count = len(arr)
    mean = arr.mean()
    minimum = arr.min()
    maximum = arr.max()

    return {
        "Total": total,
        "Count": count,
        "Mean": mean,
        "Minimum": minimum,
        "Maximum": maximum
    }

Float_Array, Replaced_Array, Cleaned_Array = (clean_sales(raw_sales))  
Discounted_Array = apply_discount_to_large_sales(Cleaned_Array)   
Summary = summarize_sales(Discounted_Array)




print("Float_Array = ",Float_Array)
print("Replaced_Array =", Replaced_Array)
print ("Cleaned Array = ", Cleaned_Array)
print ("Discounted Array = ", Discounted_Array)
print(f"Total: {Summary['Total']:.2f}")
print(f"Count: {Summary['Count']}")
print(f"Mean: {Summary['Mean']:.2f}")
print(f"Min: {Summary['Minimum']:.1f}")
print(f"Max: {Summary['Maximum']:.1f}")






Float_Array =  [120.  250.5   nan -20.  400.  150.    0.  300. ]
Replaced_Array = [120.  250.5   nan   nan 400.  150.    nan 300. ]
Cleaned Array =  [120.  250.5 400.  150.  300. ]
Discounted Array =  [120.   225.45 360.   150.   270.  ]
Total: 1125.45
Count: 5
Mean: 225.09
Min: 120.0
Max: 360.0
